name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Проверка кода
      uses: actions/checkout@v3
      
    - name: Вход в Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Установка QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ matrix.arch }}
        
    - name: Установка Buildx
      uses: docker/setup-buildx-action@v1

    - name: Сборка и публикация Docker контейнера
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}//freegpt-webui:${{ matrix.arch }}-latest

